version: "3.0"
services:
  opcua-subscribe:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "OPC UA Subscribe"
      MODULE_TYPE: "Input"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      MAX_RETRY: '1'
      REQUESTED_PUBLISHING_INTERVAL: '1000'
      REQUESTED_LIFETIME_COUNT: '100'
      REQUESTED_MAX_KEEPALIVE_COUNT: '10'
      MAX_NOTIFICATIONS_PER_PUBLISH: '100'
      PRIORITY: '10'
      NODE_ID: '3'
      VARIABLE_LIST: 'Scalar_Simulation_Float'
      SAMPLING_INTERVAL: '100'
      QUEUE_SIZE: '10'
      DISCARD_OLDEST: 'true'
      OPC_UA_SERVER: 'opc.tcp://opcuaserver.com:48010'
      OPC_UA_USERNAME: ''
      OPC_UA_PASSWORD: ''
    ports:
      - 80:80
