const env = require('../utils/env')

module.exports = {
  INGRESS_HOST: env('INGRESS_HOST', '127.0.0.1'),
  INGRESS_PORT: env('INGRESS_PORT', '8080'),
  MODULE_NAME: env('MODULE_NAME', 'OPC UA Subscribe'),
  EGRESS_URLS: env('EGRESS_URLS', ''),
  OPC_UA_SERVER: env('OPC_UA_SERVER', 'opc.tcp://localhost:26543'),
  MAX_RETRY: env('MAX_RETRY', 1),
  REQUESTED_PUBLISHING_INTERVAL: env('REQUESTED_PUBLISHING_INTERVAL', 1000),
  REQUESTED_LIFETIME_COUNT: env('REQUESTED_LIFETIME_COUNT', 100),
  REQUESTED_MAX_KEEPALIVE_COUNT: env('REQUESTED_MAX_KEEPALIVE_COUNT', 10),
  MAX_NOTIFICATIONS_PER_PUBLISH: env('MAX_NOTIFICATIONS_PER_PUBLISH', 100),
  PRIORITY: env('PRIORITY', 10),
  NODE_ID: env('NODE_ID', 3),
  VARIABLE_LIST: env('VARIABLE_LIST', 'Scalar_Simulation_Float'),
  SAMPLING_INTERVAL: env('SAMPLING_INTERVAL', 100),
  QUEUE_SIZE: env('QUEUE_SIZE', 10),
  DISCARD_OLDEST: env('DISCARD_OLDEST', true),
  OPC_UA_PASSWORD: env('OPC_UA_PASSWORD', ''),
  OPC_UA_USERNAME: env('OPC_UA_USERNAME', ''),
}
